networks:
    ipvlan15:
        external: true
        name: ipvlan15
    ipvlan16:
        external: true
        name: ipvlan16
volumes:
    crt:
        external: true
        name: step_crt_jwt 
    bind9_cache:
        driver: local
        driver_opts:
            type: nfs
            o: "addr=$NAS_ADDRESS,rw,nolock,soft,nfsvers=4"
            device: $NAS_BIND9_CACHE
    bind9_lib:
        driver: local
        driver_opts:
            type: nfs
            o: "addr=$NAS_ADDRESS,rw,nolock,soft,nfsvers=4"
            device: $NAS_BIND9_LIB
    bind9_src:
        driver: local
        driver_opts:
            type: nfs
            o: "addr=$NAS_ADDRESS,rw,nolock,soft,nfsvers=4"
            device: $NAS_BIND9_SRC
    pihole:
        driver: local
        driver_opts:
            type: nfs
            o: "addr=$NAS_ADDRESS,rw,nolock,soft,nfsvers=4"
            device: $NAS_PIHOLE
services:
    bind9:
        extends:
            file: $TEMPLATE_DNS
            service: bind9 
        volumes:
            - bind9_src:/etc/bind
            - bind9_cache:/var/cache/bind
            - bind9_lib:/var/lib/bind
        networks:
            ipvlan15:
                ipv4_address: 10.15.0.15
            ipvlan16:
                ipv4_address: 10.16.0.15 
        restart: unless-stopped
    pihole:
        extends:
            file: $TEMPLATE_DNS
            service: pihole
        volumes:
            - pihole:/etc/pihole
        networks:
            ipvlan16:
                ipv4_address: $PIHOLE_IPVLAN16_ADDRESS
        depends_on:
            - bind9
        restart: unless-stopped
    servers:
        extends:
            file: $TEMPLATE_SERVERS
            service: custom
        volumes:
            - crt:/var/local/step:ro
            - ./servers.yaml:/etc/nginx/yaml/servers.yaml
        networks:
            ipvlan16:
                ipv4_address: 10.16.0.17
        depends_on:
            - pihole
        restart: unless-stopped
