services:
    mongo:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: $DB_MONGO_INITDB_ROOT_USERNAME
            MONGO_INITDB_ROOT_PASSWORD: $DB_MONGO_INITDB_ROOT_PASSWORD
            MONGO_USER: $DB_MONGO_USER
            MONGO_PASS: $DB_MONGO_PASS
            MONGO_DBNAME: $DB_MONGO_DBNAME
            MONGO_AUTHSOURCE: $DB_MONGO_AUTHSOURCE

