networks:
    local:
        driver: bridge
services:
    server:
        extends:
            file: $TEMPLATE_SERVER
            service: nginx
        volumes:
            - ./servers.yaml:/etc/nginx/yaml/servers.yaml
        networks:
            - local
        restart: unless-stopped

