services:
    vite: 
        image: dqio/node:latest
        environment:
            VITECONFIG_HMR_HOST: $APP_VITECONFIG_HMR_HOST
            VITECONFIG_HMR_CLIENTPORT: 443
            VITECONFIG_STEPPATH: /var/local/step

