networks:
    local:
        driver: bridge
volumes:
    certbot:
        driver: local
services:
    certbot:
        extends:
            file: $TEMPLATE_LE_ROUTE53
            service: route53
        volumes:
            - certbot:/etc/letsencrypt
        networks:
            - local
        restart: unless-stopped
