#cloud-config
hostname: f44-se-300
fqdn: f44-se-300
manage_etc_hosts: true
ssh_pwauth: true
users:
  - name: admin
    groups: [wheel, docker]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: $6$dZjQf8BlA40XhNyr$bhBWYFn/tspIveCG.UF.MpcN.LOqy2fR17s4fi4MMxwtGQBNK8vRJusCEpbhYR9vJS8mFMOtEUARYcUAjcw9j/
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDjJezd+3j3CZVTSoihVSSMRfkLE3zx25nqGd+K/gGGS admin@f44-se-0.local
package_update: true
package_upgrade: true
runcmd:
  - git clone https://github.com/estuardoquan/.dotfiles.git /home/admin/dot-files
  - mkdir -p /home/admin/.config
  - stow -d /home/admin/dot-files -t /home/admin .
  - chown -R admin:admin /home/admin
  - usermod -aG docker admin
  - systemctl reboot 
