networks:
    local:
        driver: bridge
volumes:
    mongo:
        drvier: local
    config:
        driver: local
services:
    mongo:
        extends:
            file: $TEMPLATE_UNIFI_MONGO
            service: mongo
        volumes:
            - mongo:/data/db
            - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
        networks:
            - local
        restart: unless-stopped
    console:
        extends:
            file: $TEMPLATE_UNIFI_CONSOLE
            service: console
        networks:
            - local
        volumes:
            - src:/config
        depends_on:
            - mongo
        restart: unless-stopped

