- server:
      port: 443
      domain:
          subject: pihole.pi.local
      https: /var/local/step
      log: /var/log/nginx
      locations:
          - type: proxy_pass
            value: https://pihole
            include: /etc/nginx/includes/default.proxy.conf
      redirect: 80

