networks:
    local:
        driver: bridge
volumes:
    ca:
        driver: local
    crt_jwt:
        driver: local
secrets:
    provisioner_password:
        file: $PROVISIONER_PASSWORD_FILE
services:
    ca:
        extends:
            file: $TEMPLATE_STEP
            service: ca
        volumes:
            - ca:$CA_STEPPATH
        networks:
            - local
        restart: unless-stopped
    crt:
        extends:
            file: $TEMPLATE_STEP
            service: crt
        volumes:
            - crt_jwt:/var/local/step
        networks:
            - local
        depends_on:
            - ca
        restart: unless-stopped

